name: 'DBT_DEMO_01'
config-version: 2
version: 2.0
description: DBT POC
repository: https://github.com/ashimachanpuriya/dbt_demp_01.git

profile: my-snowflake-db

models:
  my_first_dbt_model:
    materialized: table
    schema: PUBLIC
    root-paths: ["models/"]


